application: edmpvote
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /vote
  script: vote.application

- url: /admin
  script: admin.application

- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest