runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /vote
  script: app.vote.application

- url: /admin/test
  script: test.testAdmin.application
  login: admin
  
- url: /admin.*
  script: app.admin.application
  login: admin

# misc files
- url: /header\.png
  static_files: header.png
  upload: header\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# gRPC endpoints
- url: /entries.*
  script: services.app

- url: /polls.*
  script: services.app

- url: /ballots.*
  script: services.app

# Default case: serve the homepage
- url: /.*
  script: app.vote.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest