application: edmpvote
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /vote
  script: vote.application

- url: /admin.*
  script: admin.application
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: vote.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest